---
- name: Test Incident
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    snow_username: admin
    snow_password: Redhat@123
    instance_id: dev64008
  tasks:
    - name: Create an incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ instance_id }}"
        state: present
        data:
          short_description: "New Ansible Tower Incident"
          description: "Installation of Active Directory on EC2 has failed"
          severity: 4
          priority: 2
          assigned_to: vsylvest
      register: win_ad_failed