---
- name: Test Incident
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    snow_username: admin
    snow_password: s!984V62729
    instance_id: dev1
  tasks:
    - name: Create an incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ instance_id }}"
        state: present
        data:
          short_description: "New Ansible Tower Incident"
          severity: 4
          priority: 2
      register: new_incident