---
- name: Test Incident
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create an incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "Creation of Windows Instance - requires network update"
          description: "Creation of Windows Instance on EC2 is successful, network update has failed"
          severity: 4
          priority: 2 
          assigned_to: vsylvest
      register: net-fail